const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const {
	scrubCommand,
	scrubMessage,
	maskHeredocBodies,
} = require("../src/scrub");
const {
	TRAILER,
	heredocCommit,
	runHook,
	git,
	tempRepo,
	tempDir,
	bashCall,
	fakeGh,
} = require("./helpers");

const bashPre = (cwd, command) => ({
	hook_event_name: "PreToolUse",
	tool_name: "Bash",
	cwd,
	tool_input: { command },
});
const PR_URL = "https://github.com/octo/repo/pull/12";
const isRoot = typeof process.getuid === "function" && process.getuid() === 0;

test("keeps trailers that credit people whose names look like AI tools", () => {
	const body = [
		"fix: thing",
		"",
		"Co-authored-by: Claude Dupont <claude@example.fr>",
		"Co-authored-by: Jules Verne <jules@example.com>",
		"Reviewed-by: Devin Smith <devin@example.com>",
		"Reviewed-by: Precursor Team <team@precursor.io>",
		"Signed-off-by: Kiro Tanaka <kiro@example.jp>",
	].join("\n");
	assert.equal(scrubMessage(body), body);
});

test("strips trailers from AI tools in every common spelling", () => {
	const lines = [
		"Co-Authored-By: Claude Opus 4 <noreply@anthropic.com>",
		"Co-authored-by: Claude Code <noreply@anthropic.com>",
		"Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
		"Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>",
		"Co-authored-by: devin-ai-integration[bot] <158243242+devin-ai-integration[bot]@users.noreply.github.com>",
		"Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		"Assisted-by: Claude",
		"Generated-by: Copilot",
		"Claude-Session: 0123abcd",
	];
	assert.equal(
		scrubMessage(`fix: thing\n\n${lines.join("\n")}\n`),
		"fix: thing\n",
	);
});

test("strips footer sentences that name Claude but keeps a colleague called Claude", () => {
	const text =
		"Adds it.\n\nGenerated by Claude\nThis PR was created with help from Claude.\nClaude: please review the parser.\n";
	assert.equal(
		scrubMessage(text),
		"Adds it.\n\nClaude: please review the parser.\n",
	);
});

test("keeps text in other scripts and accented letters", () => {
	const body = "fix: تصحيح الخطأ, 修复 bug, café naïve, Ünïcode";
	assert.equal(scrubCommand(heredocCommit(body)), heredocCommit(body));
});

test("maskHeredocBodies blanks body lines without moving offsets", () => {
	const cmd =
		"cat > s.sh <<'EOF'\ncd /nope\ngit commit -m fake\nEOF\ngit status";
	const masked = maskHeredocBodies(cmd);
	assert.equal(masked.length, cmd.length);
	assert.equal(
		masked,
		`cat > s.sh <<'EOF'\n${" ".repeat(8)}\n${" ".repeat(18)}\nEOF\ngit status`,
	);
});

test("pre-tool-use ignores cd steps and file flags inside heredoc bodies", () => {
	const dir = tempDir();
	fs.writeFileSync(path.join(dir, "msg.txt"), `feat: h\n\n${TRAILER}\n`);
	fs.writeFileSync(path.join(dir, "other.txt"), `notes\n\n${TRAILER}\n`);
	const command = `cat > s.sh <<'EOF'\ncd /nope\ngit commit -F other.txt\nEOF\ngit commit -F msg.txt`;
	runHook("pre-tool-use.js", bashPre(dir, command));
	assert.equal(fs.readFileSync(path.join(dir, "msg.txt"), "utf8"), "feat: h\n");
	assert.match(
		fs.readFileSync(path.join(dir, "other.txt"), "utf8"),
		/Co-Authored-By/,
	);
});

test("pre-tool-use only treats -F as a message file for commands that read one", () => {
	const dir = tempDir();
	fs.writeFileSync(path.join(dir, "TODO"), `list\n\n${TRAILER}\n`);
	assert.equal(
		runHook("pre-tool-use.js", bashPre(dir, "git grep -F TODO src/")),
		null,
	);
	assert.equal(
		runHook("pre-tool-use.js", bashPre(dir, "git log -F --grep TODO")),
		null,
	);
	assert.match(
		fs.readFileSync(path.join(dir, "TODO"), "utf8"),
		/Co-Authored-By/,
	);
	runHook("pre-tool-use.js", bashPre(dir, "git tag -a v1 -F TODO"));
	assert.equal(fs.readFileSync(path.join(dir, "TODO"), "utf8"), "list\n");
});

test("post-tool-use handles -c and -C flags before commit", () => {
	const repo = tempRepo();
	const out = runHook(
		"post-tool-use.js",
		bashCall(tempDir(), `git -c core.pager=cat -C ${repo} commit -m x`),
	);
	assert.equal(git(repo, ["log", "-1", "--format=%B"]), "feat: x");
	assert.match(out.hookSpecificOutput.additionalContext, /amended/);
});

test("post-tool-use ignores git commit text inside heredoc bodies", () => {
	const repo = tempRepo();
	const command = `cat > s.sh <<'EOF'\ngit commit -m fake\nEOF\necho done`;
	assert.equal(runHook("post-tool-use.js", bashCall(repo, command)), null);
	assert.match(git(repo, ["log", "-1", "--format=%B"]), /Co-Authored-By/);
});

test("post-tool-use reports when the amend itself fails", {
	skip: isRoot,
}, () => {
	const repo = tempRepo();
	const heads = path.join(repo, ".git", "refs", "heads");
	fs.chmodSync(heads, 0o555);
	try {
		const out = runHook("post-tool-use.js", bashCall(repo, "git commit -m x"));
		assert.match(out.hookSpecificOutput.additionalContext, /amend failed/);
	} finally {
		fs.chmodSync(heads, 0o755);
	}
	assert.match(git(repo, ["log", "-1", "--format=%B"]), /Co-Authored-By/);
});

test("post-tool-use reports when the GitHub edit fails", () => {
	const gh = fakeGh({
		"repos/octo/repo/pulls/12": { title: "t", body: `Adds.\n\n${TRAILER}` },
	});
	const call = bashCall(tempDir(), "gh pr create --fill", {
		stdout: `${PR_URL}\n`,
	});
	const out = runHook("post-tool-use.js", call, {
		...gh.env,
		FAKE_GH_FAIL_PATCH: "1",
	});
	assert.match(out.hookSpecificOutput.additionalContext, /edit failed/);
});

test("post-tool-use ignores gh commands quoted inside heredoc bodies", () => {
	const gh = fakeGh({});
	const command = `cat > s.sh <<'EOF'\ngh pr create --fill\nEOF\necho done`;
	assert.equal(
		runHook(
			"post-tool-use.js",
			bashCall(tempDir(), command, { stdout: `${PR_URL}\n` }),
			gh.env,
		),
		null,
	);
	assert.equal(gh.calls().length, 0);
});
